site_name: Microscope
site_url: https://microscope.com
nav:
  - Home: 'index.md'
  - 'Using Microscope' :
    - 'Microscope as a Library' : 'usage/microscope-as-a-library.md'
    - 'Microscope as a command line tool' : 'usage/microscope-as-cli.md'   
theme: readthedocs
markdown_extensions:
  - admonition
  - fenced_code